### ISSUE TITLE
lingva.ml is down

### ISSUE THREAD

**Issue by theyash14** [Socketlike/translate#1]
Hey,

I got CORS error when using Google engine.
Hence was trying with Lingva engine and **lingva.ml** appears to be down.
Although the default URL appears to be working https://lingva.thedaviddelta.com/

![image](https://github.com/Socketlike/translate/assets/53083827/d60e4771-5795-439a-ac0d-bd02fd2dccf3)

Is it possible to include multiple Lingva instances as a fallback?
https://github.com/thedaviddelta/lingva-translate#instances

I also found another engine https://simplytranslate.org/

**Comment by Socketlike** [comment]
it is possible to use a different lingva instance

pass a prop to the options named `url` with the url

however i will (likely?) not be implementing fallbacking directly into the engine itself

**Comment by Socketlike** [comment]
added support for SimplyTranslate @ v1.0.9

**Comment by theyash14** [comment]
Thanks for  adding support for Simply Translate.
